"""Poolhound info — the public landing page.

WHAT THIS TAB IS FOR

The public address is a public address, and what anonymous visitors used to
land on was Home: this household's current chlorine, its lab history, its
runtime. Nothing there was secret — Home is derived from the same measurements
the chemistry reference is — but it is a dashboard, and a dashboard answers
"how is it doing" to somebody who has not yet been told what "it" is. The first
screen a stranger sees should say what the thing does.

So Home moved behind the sign-in, where the people who own the pool are, and
this took its place.

THE PICTURES ARE OF A POOL THAT DOES NOT EXIST

Every screenshot on this page comes from `bin/demo-data` — a synthetic pool
built into a temporary directory by `bin/screenshots`, which asserts its own
isolation before it renders anything. That is deliberate and it is the whole
reason screenshots are allowed here at all: a live public dashboard would be
this household's readings, and a hand-cropped screenshot of the real one would
be the same thing with extra steps and no check. A generated picture of a
generated pool can be regenerated by anyone who clones this, and it cannot
leak, because there is nothing in it to leak.

The captions say so on the page as well. A reader who is not told a figure is
a demonstration will read it as live data, and this page's entire argument is
that a number should say where it came from.
"""

import html
import re

from .icons import icon

# WHAT THE APP IS, as against what it does. The three below are the does;
# this is the is, and the distinction was the defect: the masthead's only
# statement of the product was three clauses of behaviour run into one
# sentence, so a reader who had never heard of this arrived at a list of
# verbs with nothing naming the category they belonged to. A stranger needs
# to be told what a thing IS before being told what it does.
#
# One phrase, three readers: the browser tab, the meta description and the
# line under the masthead. Typing the category into the <title> separately is
# how a product comes to call itself two things in one document.
CATEGORY = "remote pool management, chemistry tracking and analytics"

# THERE IS NO SEPARATE HEADLINE, AND THAT IS THE SECOND TIME THIS WAS WRONG.
#
# The hero first set WHAT_IT_IS at display size and it ran to nine lines: a
# forty-word sentence is a standfirst, not a headline, and at 44px it pushed
# the whole page below the fold. The fix was a 44px line above it stating the
# thesis — "dose from what your pool does, not from somebody else's chart" —
# which is PURPOSE[1]'s clause in different words, sitting directly above
# PURPOSE[1]. The first screen made the same promise twice, once at display
# size, and a reader counting the things this does would have counted four.
#
# So the hero opens with the wordmark in the header, then WHAT_IT_IS as the
# lead, then the three AS THREE. The lead carries the weight a headline
# would — see `.hero .tagline` in style.py — because the thing a stranger
# needs first is what this IS, and that sentence is the only place it is said.
WHAT_IT_IS = (
    f"Poolhound is a {CATEGORY} tool for one pool and its spa \u2014 one address "
    "for the equipment panel, and one record of every reading, every dose and "
    "what happened next.")


def page_title():
    """The browser tab, on both builds. The wordmark alone said nothing: a tab,
    a bookmark and a search result are all title-only, and "poolhound" is a
    name a reader has no reason to recognise."""
    return f"poolhound \u2014 {CATEGORY}"


# WHAT THIS IS FOR. THREE THINGS, AND THEY ARE NOT THE SAME THING.
#
# This was got wrong once already, one level up: the masthead tagline used to
# describe only the measurement half, leaving the two things a reader is most
# likely to have come for -- reaching the controller, and working out the
# volume -- unmentioned on the page that offers them. It was fixed there, and
# then this file opened its own first section with "a pool is a chemistry
# experiment that somebody swims in" and made exactly the same cut one level
# down. A landing page whose first paragraph names one of three purposes is a
# landing page that has lost the plot of the product.
#
# So the three are declared HERE, once, and the masthead is assembled from
# them -- see masthead(). seams.py knows they live in this file. The page
# cannot now describe a different product from the header above it.
#
# (icon, heading, the clause the masthead uses, the paragraph the page uses)
PURPOSE = [
    ("plug", "Replace the panel's remote with any browser",
     "Reach a pool controller that has no password of its own, safely, from "
     "anywhere.",
     "The panel is driven by its PDA: one handheld, in one place, and whoever "
     "is holding it. Poolhound puts the same circuits and setpoints in any "
     "phone or browser, at one address that works from the garden or from "
     "another country \u2014 no port forwarding, no VPN, nothing to install. The "
     "panel itself is never exposed: a sampler on the house network connects "
     "outward and waits. It is built on "
     "[AqualinkD](https://github.com/sfeakes/AqualinkD), the open-source "
     "project that speaks the panel's undocumented RS485 protocol; poolhound "
     "adds the sign-in, the outward connection and the record of what was "
     "done."),
    ("target", "Dose from what this pool actually does",
     "Dose from what this pool actually does rather than from a chart written "
     "for somebody else's.",
     "Every dose is recorded with what happened next, so the advice is fitted "
     "to this pool's own response rather than read off a band written for a "
     "pool nobody here has seen. Where two labs disagree that is kept as a "
     "disagreement, not averaged into a number neither of them reported."),
    ("shapes", "Know how much water there really is",
     "Find out how much water there really is, which every dose figure "
     "multiplies through.",
     "Every dose figure multiplies through the volume, so a guess there is a "
     "wrong answer everywhere else. Trace a photograph of the pool or pick a "
     "stock shape, and get an uncertainty band instead of one confident "
     "number. Pool and spa are measured separately."),
]


def masthead(public=True):
    """What this is, then the three things it does, under the wordmark.

    Both builds carry it, and it is the only statement of what this is that an
    anonymous visitor sees before they have scrolled anything. It used to be
    one sentence of three clauses joined with spaces -- every word of it true,
    and all of it answering "what does it do" to somebody who had not yet been
    told what it was, in a 1.55-line-height paragraph where three distinct
    promises read as one long qualification of each other.

    So the shape says what the content is: a sentence that names the category,
    and then the three AS THREE. Assembled from PURPOSE rather than typed, so
    it cannot come to describe a different product from the landing page
    directly below it -- which is a thing that has happened twice.

    This is the function name that used to be `tagline()`. It returns a block
    rather than a line now, and a name that has stopped being true is worse
    than no name.
    """
    does = "".join(
        f'<li>{icon(ic, 15)}<span>{html.escape(clause, quote=False)}</span></li>'
        for ic, _, clause, _ in PURPOSE)
    # WRAPPED, so the two can be laid out against each other. They were bare
    # siblings of the page wrapper, which meant the statement and the three
    # things it does could only ever stack — and on a 1140px page that left
    # the right-hand half of the first screen empty. One container is all the
    # stylesheet needs to put them side by side; see `.hero` in style.py.
    # THE HERO IS FOR A STRANGER, AND THE DASHBOARD IS NOT.
    #
    # The authenticated build opens on Home, which answers "how is the water
    # doing" to somebody who already knows what this is. A 44px statement of
    # the product's thesis above that pushes the first reading 400px down the
    # page to tell an operator something they came in knowing. The public
    # build has the opposite problem and is why the hero exists.
    #
    # So the same two pieces, two sizes: `.hero` on the public build, `.hero
    # compact` on the authenticated one, where the lead stands down to the
    # smallest text on the page and the three are hidden outright.
    cls = "hero" if public else "hero compact"
    return (f'<div class="{cls}">\n'
            f'<p class="tagline">{html.escape(WHAT_IT_IS, quote=False)}</p>\n'
            f'<ul class="does">{does}</ul>\n'
            f'</div>')


# The figures, in the order they are shown. (card file, screen label, tab or
# None, alt text, caption).
#
# `tab` is what the caption links to. Two of these are screens the public build
# does not contain, and they are routed through help._tablink(), which renders
# a link on the authenticated page and "(needs sign-in — not on this page)" on
# the public one. A caption that linked to a tab this file does not have would
# be a dead link on the one build where most readers of this page are.
FIGURES = [
    ("home-light.png", "Home", "home",
     "The Home screen: two ranked actions, each with the dose it would take, "
     "above a row of tiles giving the current value of every measure with its "
     "source and its age.",
     "What to do next, ordered by consequence rather than by how far a number "
     "sits outside its band — and the dose that would do it, computed for this "
     "pool's volume rather than read off a chart."),
    ("control-light.png", "Pool control", "control",
     "The Pool control screen: one card per circuit showing the panel's last "
     "reported state with on and off buttons, and below them a setpoints "
     "section with each heater, freeze protection and the salt cell output.",
     "Every circuit and every setpoint the panel exposes, with what the panel "
     "itself last reported beside what it was asked for. A command that has "
     "not been confirmed says so."),
    # NOT A POOLHOUND SCREEN, and the caption says so first. It is the
    # optional page on the author's Pi, poolhound local
    # (deploy/poolhound-local.html), photographed
    # against the same synthetic pool as the rest; tab is None because there
    # is nothing in either build to link to.
    ("poolhound-local-dark.png", "poolhound local", None,
     "poolhound local, a dark page on the house network: a grid of circuits, each with "
     "its friendly name, the panel's own label beneath it and an on/off "
     "switch, with the filter pump, sheer descent and solar heat on.",
     "Optional, and installed by nothing here: a page served by the Pi itself, "
     "on the house network, talking to AqualinkD directly. It works when the "
     "internet does not, and shows poolhound's record of every change at the "
     "panel. poolhound runs the same without it; a copy is in "
     "deploy/poolhound-local.html."),
    ("chemistry-light.png", "Pool chemistry", "chemistry",
     "The Pool chemistry screen: for each factor, what pushes it, how strongly, "
     "and what to do about it.",
     "The reference half — what each measure does, what moves it, and how the "
     "six of them pull against each other. Public, because it is the part that "
     "is useful to somebody else's pool too."),
    ("volume-light.png", "Pool Volume Calculator", "volume",
     "The Pool Volume Calculator: stock pool shapes to choose from and a tool "
     "for tracing a photograph, with the computed volume and its uncertainty "
     "band.",
     "Trace a photograph of a pool, or pick a stock shape. Every dose on every "
     "other screen is a volume multiplied by a coefficient, so this is the "
     "number the rest of it rests on."),
    ("ask-light.png", "Ask AI", "ask",
     "The Ask AI screen: a question box, a note saying exactly what is sent "
     "and where, and below it the full context the model receives.",
     "The advantage over asking a chatbot is that it is tuned to THIS pool's "
     "parameters \u2014 its volume, its targets, its actual readings and the doses "
     "that have gone in. It answers from the record rather than from pool "
     "chemistry in general, and the screen prints everything it sends."),
    ("collection-light.png", "Collection", "collection",
     "The Collection screen: one card per data source with when it last ran "
     "and what it returned, then a table of every attempt.",
     "Every attempt to fetch anything, whether it worked or not — including "
     "whether an alarm that was raised actually reached somebody."),
]

# Where the numbers come from. Deliberately not a diagram: Help has two, drawn
# properly, and a third simplified one here would be a second copy of the
# architecture that could disagree with them.
SOURCES = [
    ("plug", "The pool panel",
     "A sampler on a Raspberry Pi reads the controller on the house network and "
     "pushes readings outward. Water and air temperature, what is running, what "
     "every setpoint is, and the salt cell's output."),
    ("flask", "A sensor in the water",
     "A floating pod measures free chlorine and pH continuously and posts a "
     "water sample away for a full panel every few weeks."),
    ("beaker", "A counter test",
     "Results from carrying a sample in to a pool store, which measures things "
     "no daily sensor covers — alkalinity, cyanuric acid, calcium, salt."),
    ("drop", "What was actually poured in",
     "Every dose, logged with its strength and its amount. This is the half "
     "that makes the rest fittable: without knowing what went in, a change in "
     "the water is an observation rather than a measurement."),
]


# A purpose paragraph may credit a project by linking it, written
# [text](https://...). ESCAPED FIRST and linked after, so the only markup that
# can reach the page is an anchor this pattern built — never a tag that was in
# the text — and only to an https URL with no quote or space in it. The URL's
# host must be on the publishability roster like any other outbound link.
_LINK = re.compile(r"\[([^\]\[]+)\]\((https://[^\s()\"'<>]+)\)")


def _prose(text):
    return _LINK.sub(lambda m: f'<a href="{m.group(2)}" rel="noopener">'
                               f'{m.group(1)}</a>',
                     html.escape(text, quote=False))


def _fig(card, label, tab, alt, caption, public):
    """One screenshot, its name, and what it is a picture of."""
    from .help import _tablink
    name = _tablink(tab, label, public=public) if tab else html.escape(label)
    return f'''<figure class="shot">
  <img src="screenshots/{html.escape(card, quote=True)}" width="880" height="555"
       loading="lazy" decoding="async" alt="{html.escape(alt, quote=True)}">
  <figcaption><b>{name}</b> {html.escape(caption)}</figcaption>
</figure>'''


def panel(public=False):
    """The whole tab. Present on both builds — the authenticated one keeps it so
    the explanation does not become something only strangers can read."""
    figures = "".join(_fig(*f, public) for f in FIGURES)
    sources = "".join(
        f'''<div class="card source-card">
      <div class="srch">{icon(ic, 16)}<b>{html.escape(name)}</b></div>
      <p class="sub">{html.escape(what)}</p>
    </div>''' for ic, name, what in SOURCES)

    # THE SAME DRAWING HELP USES, not a second one. Both panels are in the same
    # file, so it is asked for its own id prefix: two copies of an SVG on one
    # page means two elements answering to the same id, which makes the figure's
    # aria-labelledby ambiguous and leaves the arrow markers resolving to
    # whichever came first.
    from .help import _arch_glance, _arch_simple
    diagram = _arch_simple(idp="info-")
    glance = _arch_glance()

    purposes = "".join(
        f'''<div class="card">
      <h3>{icon(ic, 17)}<span>{html.escape(head)}</span></h3>
      <p>{_prose(body)}</p>
    </div>''' for ic, head, _clause, body in PURPOSE)

    return f'''<section id="info-glance">
  <h2>Three pieces: the panel, the Pi and the web server</h2>
  <div class="showpiece">{glance}</div>
</section>

<section id="info-what">
  <h2>What poolhound is for</h2>
  <p class="lede">Three problems. They belong to the same pool, which is why
  one tool holds all three — but they are not the same problem, and most of
  what is written about pools answers only the middle one.</p>
  <div class="purpose">{purposes}</div>
  <p class="sub">Underneath all three is one record: every reading, every dose,
  and what happened next. The output is a small number of things worth doing,
  each with an amount, and each traceable back to the measurement that asked
  for it.</p>
</section>

<section id="info-sources">
  <h2>What it reads</h2>
  <p class="sub">Four sources, none of which agrees with the others all the
  time. Where two instruments disagree that is recorded as a disagreement — it
  is usually the pool having moved between the two dates — and neither is
  quietly averaged away or called wrong.</p>
  <div class="srcgrid">{sources}</div>
</section>

<section id="info-screens">
  <h2>What it looks like</h2>
  <div class="v-note">{icon("camera", 15)} <b>These are a pool that does not
  exist.</b> Every figure below is rendered from a synthetic dataset by
  <code>bin/screenshots</code>, so nothing on this page is anybody's real
  water. The live screens look like this and hold real readings.</div>
  <div class="shotgrid">{figures}</div>
</section>

<section id="info-try">
  <h2>What you can use here</h2>
  <p class="sub">Three of these screens need no sign-in, because they are the
  part that is useful to a pool that is not this one.</p>
  <ul class="tryish">
    <li><a href="#volume" data-tab-link="volume">Pool Volume Calculator</a> —
      trace a photograph or pick a stock shape, and get a volume with an honest
      uncertainty band rather than a single confident number.</li>
    <li><a href="#chemistry" data-tab-link="chemistry">Pool chemistry</a> —
      what each measure does, what moves it, how far, and why the six of them
      cannot all be satisfied at once.</li>
    <li><a href="#help" data-tab-link="help">Guide</a> — how this one is built,
      down to the wiring and the adapter, if you want to build the same
      thing.</li>
  </ul>
</section>

<section id="info-built">
  <h2>How it is put together</h2>
  <p class="sub">Five pieces and the direction of every arrow. The one that
  matters is the arrow out of the house: the equipment panel has no password of
  its own, so nothing outside opens a connection toward it &mdash; the Pi pushes
  a sample out every fifteen minutes and holds one connection open for commands
  to come back down.</p>
  <div class="showpiece">{diagram}</div>
  <p class="sub">Python and its standard library, almost entirely. The pages
  are rendered to static files — this one and a second one with the private
  screens in it, which is a different file rather than the same page with
  things hidden. The equipment panel has no authentication of its own, so it is
  never exposed and never proxied: the sampler on the house network connects
  outward and waits. The readings live on network storage that outlives the
  machine serving them.</p>
  <p class="sub">The long version, including the parts list and the wiring, is
  on <a href="#help" data-tab-link="help">Guide</a>.</p>
</section>'''
